services:
  postgres:
    image: postgres:17
    container_name: postgres_container 
    ports:
      - "5432:5432"
    environment:
       POSTRES_DB: book_db
       POSTGRES_USER: admin 
       POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
    - bookmanager-network
  bookmanager:
    build: .
    container_name: bookmanager_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookStorePP
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - postgres
    restart: always
    networks:
    - bookmanager-network
    
volumes:
  postgres_data:
networks:
  bookmanager-network:
    driver: bridge
